### ISSUE TITLE
Description has multiple languages

### ISSUE THREAD

**Issue by razzeee** [flathub/com.adilhanney.saber#68]
You can tag the different languages into different blocks and mark them with the correct language. That way users of gnome sofware/kde discover and those languages, get shown the correct translation

**Comment by adil192** [comment]
Looks like this is fixed in the Pop!_Shop, although the [Flathub](https://flathub.org/apps/com.adilhanney.saber) website still shows all the languages -- maybe it just hasn't updated yet

![image](https://github.com/flathub/com.adilhanney.saber/assets/21128619/2138c997-0e79-44da-b4ef-c0a8ec09406b)

**Comment by razzeee** [comment]
Fixed on the website. If you still want to improve it, have a look at https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines and maybe change the description to not mirror the summary in parts

**Comment by razzeee** [comment]
Yes, you can just use the same mechanisim for summary and images.

But the website doesn't use those (yet)
